events {}

http {
    upstream http_backend {
        server app1:8080;
        server app2:8080;
        server app3:8080;
    }

    upstream grpc_backend {
        server app1:50051;
        server app2:50051;
        server app3:50051;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://http_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ws {
            proxy_pass http://http_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
        }
    }

    server {
        listen 81 http2;

        location / {
            grpc_pass grpc://grpc_backend;
        }
    }
}